<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MathInterpreter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<Compile Include="FunctionArgsException.fs" />
	<Compile Include="LexerException.fs" />
	<Compile Include="ParseException.fs" />
	<Compile Include="DivisionByZeroException.fs" />
    <Compile Include="Simple_Interpreter.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cloo.clSharp" Version="1.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>